#!/bin/bash

cmake \
      -DCMAKE_BUILD_TYPE=Debug \
      -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR} \
      -DCMAKE_PREFIX_PATH="$BOOST_DIR" \
      -DPELERAD_DIM=3 \
      -DPELERAD_ENABLE_MPI=OFF \
      -DPELERAD_ENABLE_OPENOMP=OFF \
      -DPELERAD_ENABLE_EB=OFF \
      -DPELERAD_ENABLE_LINEARSOLVERS=ON \
      -DPELERAD_ENABLE_HYPRE=OFF \
      -DPELERAD_ENABLE_PARTICLES=OFF \
      -DPELERAD_ENABLE_HIP=OFF \
      -DPELERAD_ENABLE_TESTS=ON \
      -DPELERAD_ENABLE_FCOMPARE=OFF \
      -DAMREX_HOME_DIR=${AMREX_HOME} \
      -DHYPRE_LIBRARIES=${HYPRE_DIR}/lib/libHYPRE.a \
      -DHYPRE_INCLUDE_DIRS=${HYPRE_DIR}/include \
      ..
