#!/bin/bash

cmake \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=${PELERAD_HOME}/install \
      -DCMAKE_CXX_COMPILER=$(which CC)\
      -DPELERAD_DIM=3 \
      -DPELERAD_ENABLE_MPI=OFF \
      -DPELERAD_ENABLE_EB=ON \
      -DPELERAD_ENABLE_LINEARSOLVERS=ON \
      -DPELERAD_ENABLE_HYPRE=OFF \
      -DPELERAD_ENABLE_PARTICLES=OFF \
      -DPELERAD_ENABLE_CUDA=OFF \
      -DPELERAD_ENABLE_HIP=ON \
      -DPELERAD_ENABLE_TESTS=ON \
      -DPELERAD_ENABLE_FCOMPARE=OFF \
      -DAMREX_HOME_DIR=${AMREX_HOME} \
      ..
